apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metabase
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  url: https://github.com/andrebassi/flux-cd-sample
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metabase
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: metabase
  targetNamespace: metabase
  timeout: 3m0s
  wait: true